apiVersion: v1
kind: Service
metadata:
  name: {{ include "zicops-app.fullname" . }}
  labels:
    {{- include "zicops-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: zapp-prod
      protocol: TCP
      name: zapp-prod
  selector:
    {{- include "zicops-app.selectorLabels" . | nindent 4 }}
