name: ZicopsApp CI/CD - GCP Mumbai South-1-a

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  PROJECT_ID: zicops-one
  SERVICE_NAME: zicops-app

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  npm_ci_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
  docker_build_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} --build-arg GO_MODULES_TOKEN=${{secrets.GO_MODULES_TOKEN}} .
  approval_staging:
    needs: docker_build_check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Get Approvals for Staging Deployment
      uses: trstringer/manual-approval@v1.8.0
      with:
         secret: ${{ github.TOKEN }}
         approvers: jtas01,saraswatpuneet
         minimum-approvals: 1
         issue-title: "Deploying ZicopsApp to staging after a fresh build"
         exclude-workflow-initiator-as-approver: false
         timeout-minutes: 5
  build_push_image:
    needs: approval_staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Build the Docker image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} --build-arg GO_MODULES_TOKEN=${{secrets.GO_MODULES_TOKEN}} .
    - name: add latest tag
      run: |-
        docker tag gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} gcr.io/$PROJECT_ID/$SERVICE_NAME:latest
    - run: |
        gcloud auth configure-docker -q
    - run: |
        gcloud components install gke-gcloud-auth-plugin
    - name: Push the Docker image
      run: |-
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA}
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

  deploy_staging:
    needs: build_push_image
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: zicops-production-cost-one
      GKE_ZONE: asia-south1-a
    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - run: |
        gcloud auth configure-docker -q
    - run: |
        gcloud components install gke-gcloud-auth-plugin
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: replace environment variable in values.yaml
      run:  envsubst '${GITHUB_SHA}' < k8s/zicops-app/values.template.yaml > k8s/zicops-app/values.yaml
    - name: Deploy to zicops-prod-cost-one
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade -n staging zicops-app k8s/zicops-app --install --wait --atomic

  approval_production:
    needs: deploy_staging
    runs-on: ubuntu-latest
    steps:
    - name: Get Approvals for Zicops One Production Deployment
      uses: trstringer/manual-approval@v1.8.0
      with:
         secret: ${{ github.TOKEN }}
         approvers: jtas01,saraswatpuneet
         minimum-approvals: 1
         issue-title: "Deploying to zicops one production cluster"
         exclude-workflow-initiator-as-approver: false
         timeout-minutes: 5

  deploy_production:
    needs: approval_production
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: zicops-dot-com-1
      GKE_ZONE: asia-south1-a
    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - run: |
        gcloud auth configure-docker -q
    - run: |
        gcloud components install gke-gcloud-auth-plugin
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: replace environment variable in values.yaml
      run:  envsubst '${GITHUB_SHA}' < k8s/zicops-app/values.template.yaml > k8s/zicops-app/values.yaml
    - name: Deploy to zicops-prod-cost-one
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade -n production zicops-app k8s/zicops-app --install --wait --atomic