name: Zicopsapp-Integration-Test

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: ./test.js
        threshold-duration: "1s"
        summary-trend: true

