name: Zicopsapp-Integration-Test

on:
  workflow_dispatch:
    inputs:
      graphql-endpoint:
        description: 'GraphQL endpoint URL'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run k6 test
      uses: loadimpact/k6-github-action@v3.3.1
      with:
        script: ./test.js
        env: |
          K6_GRAPHQL_ENDPOINT=${{ github.event.inputs.graphql-endpoint }}
          K6_GRAPHQL_MUTATION="mutation { login { id first_name last_name status role is_verified is_active gender created_by updated_by created_at updated_at email phone photo_url __typename } }"
        threshold-duration: "1s"
        summary-trend: true


